NHLSolution/LottoQuickPicks/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace LottoQuickPicks.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

NHLSolution/LottoQuickPicks/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LottoQuickPicks.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

NHLSolution/LottoQuickPicks/Pages/LottoQuickPicks.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LottoQuickPicks.Pages
{
    public class LottoQuickPicksModel : PageModel
    {
        [BindProperty]
        public string? Username { get; set; }

        [BindProperty]
        public string? LottoType { get; set; } = "Lotto649";
        [BindProperty]
        public int QuickPicks { get; set; } = 3;

        public string? InfoMessage { get; private set; }
        public string? ErrorMessage { get; private set; }

        public List<int[]> QuickPickNumbers { get; private set; } = new();

        public void OnPostGenerateNumbers()
        {
            if (string.IsNullOrWhiteSpace(Username))
            {
                ErrorMessage = "strong>usaername</strong> is required and cannot be blank";

            }
            else
            {
                QuickPickNumbers.Clear();

                Random rand = new();
                for (int quickCount = 1; quickCount <= QuickPicks; quickCount++)
                {
                    if (LottoType.ToUpper() == "LOTTO649")
                    {
                        int[] currentLottoQuickPicks = new int[6];
                        for (int count = 1; count <= 6; count++)
                        {
                            currentLottoQuickPicks[count - 1] = rand.Next(1, 50);
                        }

                        Array.Sort(currentLottoQuickPicks);
                        QuickPickNumbers.Add(currentLottoQuickPicks);

                    }
                }
                InfoMessage = $"hello {Username}";
            }
            
        }

        public IActionResult OnPostClear()
        {
            Username = null;
            InfoMessage = null;
            ErrorMessage = null;
            return RedirectToPage();
        }
        public void OnGet()
        {
        }
    }
}

NHLSolution/LottoQuickPicks/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LottoQuickPicks.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

NHLSolution/LottoQuickPicks/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

NHLSolution/LottoQuickPicks/Pages/LottoQuickPicks.cshtml
@page
@model LottoQuickPicks.Pages.LottoQuickPicksModel
@{
    ViewData["Title"] = "Lotto Quick Picks";

    <h1>Lotto Quick Picks</h1>
    <p>
        This is your lucky day.
        Enter your name, select a lotto type, and the
        number of quick picks to generate
    </p>
}

@if (Model.InfoMessage is not null)
{
    <div class="alert alert-info">
        @Html.Raw(Model.InfoMessage)
    </div>

}
@if (Model.ErrorMessage is not null)
{
    <div class="alert alert-info">
        @Html.Raw(Model.ErrorMessage)
    </div>

}
@{
    if (Model.QuickPickNumbers.Count > 0)
    {
        int quickPickCount = 1;
        foreach (int[] quickPicks in Model.QuickPickNumbers)
        {
            <p>Quick Pick Number @quickPickCount</p>
            <table>
                <tbody>
                    <tr>
                        @foreach (int currentNumber in currentQuickPick)
                        {
                            <td>@currentNumber</td>
                        }
                    </tr>
                </tbody>
            </table>
        }
    }
}

<form method"post">
    <div class="row mb-3">
        <label asp-for="Username" class="col-sm-2 col-form-label">Username</label>
        <div class="col-sm-10">
            <input type="text" asp-for="Username" class="form-control">
        </div>

    </div>
    <div class=" row">
        <button type="submit" asp-page-handler="GenerateNumbers" class="btn btn-primary">Generate</button>
        <button type="submit" asp-page-handler="Clear" class="btn btn-secondary">Cancel</button>
    </div>
</form>

NHLSolution/LottoQuickPicks/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LottoQuickPicks</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LottoQuickPicks.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">LottoQuickPicks</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/LottoQuickPicks">Lotto Quick Picks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - LottoQuickPicks - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>